### ISSUE TITLE
철벽 보안 알고리즘 질문

### ISSUE THREAD

**Issue by gvsteve24** [kokoa-naverAIboostcamp/algorithm#7]
암호문(암호화 된 문장)은 평문을 제 2 공개키를 만든 규칙의 반대로 재배치하여 만들어진다.

**질문**
평문 - 1공개키 - 2공개키 - 암호문 순으로 암호화가 이루어진다고 하면
역순으로 평문을 만드는 거라고 생각해서 
암호문 - 2공개키 - 1공개키 - 평문으로 풀면 문제가 성립이 안되는데 
어떻게 이해해야 문제를 이해하고 푸는걸까요? 

```python
# test case
n = int(input())
for i in range(n):
    m = int(input())
    p1 = input().split()
    p2 = input().split()
    enc = input().split()
    en_dict = dict()
    result = []
    for frm, tgt in zip(p2, enc):
        en_dict[frm] = tgt
    for wrd in p1:
        result.append(en_dict[wrd])
    print(*result)
```

그래서 문제는 무시하고 예시 케이스로 대조해가면서 규칙을 찾아서 풀었습니다.
그랬던게 엄청 비효율적이어서 질문합니다! 제가 문제를 이해하지 못하는 건가요?

**Comment by N-analyst** [comment]
문제를 조금 잘못 이해하고 있는거 같습니다...
`제 2 공개키` -> `제 1 공개키`로 바꾸는 순서를 그대로
`암호키` -> `평문`으로 바꾸는 겁니다!!

![image](https://user-images.githubusercontent.com/69948072/124948407-9f04e800-e04b-11eb-94a9-36967b65a3ef.png)

위 그림을 보시면 조금 더 이해하기 쉬울 꺼 같습니다!!

**Comment by gvsteve24** [comment]
그걸 그렇게 이해해야되는 건가요... 음 그러면 제 1 공개키와 평문은 같은 개념으로 받아들여야 할까요?

평문(암호화 되지 않은 문장)은 제 1 공개키와 같이 여러 단어들로 되어있지만, 제 1 공개키와 다르게 각 단어들은 중복이 가능하다. > 저는 이 문장 때문에 평문에서 중복을 제외한 단어들로 구성한게 제 1 공개키라고 생각했어요. 그래서 재배치 이전에 어떤 규칙이 하나 더 있는걸로 생각했던거 같습니다.

결론을 내자면 암호화를 하는 이유가 어떤 규칙을 둔 두개의 키(제 1 공개키, 제 2 공개키)로 암호문으로부터 평문을 구할수 있게 하는것이다 라고 생각하면 될까요?

**Comment by N-analyst** [comment]
결론을 내자면 암호화를 하는 이유가 어떤 규칙을 둔 두개의 키(제 1 공개키, 제 2 공개키)로 암호문으로부터 평문을 구할수 있게 하는것이다 라고 생각하면 될까요?
- 네 맞습니다!!

근데 여기서 말하는 평문은 제 1 공개키와 다르게 각 단어들은 중복이 가능하다는 의미는 우선 제2 공개키를 제1 공개키로 바꾸는 순서로 암호문을 평문으로 복원을 하게 되는데 제2 공개키가 제1 공개키로 바꾸는 순서가 유일하게 하나로 결정되려면 제1 공개키와 제2 공개키의 단어들은 다 unique해야 합니다. 그래서 제 1 공개키는 중복이 없는 단어라고 말한 것이고, 이렇게 순서가 결정 된다면 암호문은 중복이 있어도 위에서 구한 순서 그대로 배치하면 되기때문에 평문으로 복원이 가능하여 중복이 가능하다고 쓴 것 같습니다. 즉, 암호문에 중복단어가 있어도 제1 공개키와 제2공개키의 단어가 중복이되지않아 배치 방법이 유일하게 정해진다면 상관 없다는 의미이고 test case에서 암호문에 중복이 있다는 것을 표현하기 위해 쓴 내용 같습니다.

**Comment by gvsteve24** [comment]
답변이 충분히 되었습니다. 이슈는 닫도록 하겠습니다!~
